WebAppYte-master/WebAppYte-master/WebAppYte/Areas/Admin/Controllers/ThongKeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppYte.Models;
using OfficeOpenXml;
using OfficeOpenXml.FormulaParsing.Excel.Functions.RefAndLookup;
using OfficeOpenXml.Table;
using System.Web.Http.Results;
using System.Xml.Linq;
using System.IO;

namespace WebAppYte.Areas.Admin.Controllers
{
    public class ThongKeController : Controller
    {
        private modelWeb db = new modelWeb();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DangXuatAd()
        {
            Session["userAdmin"] = null;
            return RedirectToAction("Index", "HomeAdmin");
        }

        [HttpPost, ActionName("ExportExcel")]
        public ActionResult ExprotExcel(DateTime startDate, DateTime endDate)
        {
            string templatePath = Server.MapPath("~/Content/Template.xlsx");

            
            List<NguoiDung> nguoiDungs = db.NguoiDungs.Where(d => d.tendn == "admin").ToList();
            List<DatLich> datLiches = db.DatLiches.Where(d => d.ngaydat >= startDate && d.ngaydat <= endDate && d.trangthai == 2).ToList();


            List<ExportExcelTemplate> template = new List<ExportExcelTemplate>();
            

            foreach(DatLich datlich in datLiches)
            {
                ExportExcelTemplate exportExcelTemplate = new ExportExcelTemplate
                {
                    chinhanh = datlich.CaKham.NguoiDung.ChiNhanh.diachi,
                    bacsi = datlich.CaKham.NguoiDung.hoten,
                    khoa = datlich.CaKham.NguoiDung.Khoa.tenkhoa,
                    tenbenhnhan = datlich.hoten,
                    ngaysinh = ((DateTime)datlich.ngaysinh).ToString("dd/MM/yyyy"),
                    ngaykham =((DateTime)datlich.CaKham.ngaykham).ToString("dd/MM/yyyy"),
                    cakham = datlich.CaKham.ca,
                    trangthai = datlich.trangthai.Value,
                    sodienthoai = datlich.sdt
       
                };

                template.Add(exportExcelTemplate);
            }

            TExportExcelTemplate exportExcel = new TExportExcelTemplate
            {
                datas = template,
                username = nguoiDungs[0].hoten,
                start_date = startDate.ToString("dd/MM/yyyy"),
                end_date = endDate.ToString("dd/MM/yyyy")
            };

            //var fileBytes = System.IO.File.ReadAllBytes("path_to_your_excel_file.xlsx"); 
            //return File(fileBytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "filename.xlsx");
            return Json(exportExcel);
        }

        [HttpPost, ActionName("thongkesoluongcakham")]
        public ActionResult ThongKeSoLuongCaKham(DateTime startDate, DateTime endDate)
        {
            List<DatLich> datLiches = db.DatLiches.Where(d => d.ngaydat >= startDate && d.ngaydat <= endDate && (d.trangthai == 1 || d.trangthai == 2)).ToList();
            int soluongdakham = 0;
            int soluongchuakham = 0;
            List<int> result = new List<int>();
            foreach (DatLich datLich in datLiches)
            {
                if (datLich.trangthai == 1)
                {
                    soluongchuakham += 1;
                }
                else soluongdakham += 1;
            }


            result.Add(soluongdakham);
            result.Add(soluongchuakham);
            return Json(result);
        }

        [HttpPost, ActionName("thongkesoluongcakhamtheobacsi")]
        public ActionResult ThongKeSoLuongCaKhamTheoBacSi(DateTime startDate, DateTime endDate)
        {
            List<DatLich> datLiches = db.DatLiches
                .Where(d => d.ngaydat >= startDate && d.ngaydat <= endDate && d.trangthai == 2)
                .ToList();

            List<NguoiDung> nguoiDungs =db.NguoiDungs.ToList();
            
            Dictionary<string, int> myDictionary = new Dictionary<string, int>();
            foreach (NguoiDung nguoiDung in nguoiDungs)
            {
                myDictionary.Add(nguoiDung.hoten.Trim() + " - " + nguoiDung.tendn.Trim(), 0);
            }
            foreach (DatLich datLich in datLiches)
            {
                if(myDictionary.ContainsKey(datLich.CaKham.NguoiDung.hoten.Trim() + " - " + datLich.CaKham.NguoiDung.tendn.Trim()))
                { 
                    myDictionary[datLich.CaKham.NguoiDung.hoten.Trim() + " - " + datLich.CaKham.NguoiDung.tendn.Trim()]++;
                }
            }

            var array = myDictionary.Select(kvp => new { bacsi = kvp.Key, soluong = kvp.Value }).ToArray();
            return Json(array);
        }
    }

    class ExportExcelTemplate
    {
        public int stt;
        public string chinhanh;
        public string bacsi;
        public string khoa;
        public string tenbenhnhan;
        public string ngaysinh;
        public string sodienthoai;
        public string ngaykham;
        public string cakham;
        public int trangthai;
    }

    class TExportExcelTemplate
    {
        public List<ExportExcelTemplate> datas;
        public string username;
        public string start_date;
        public string end_date;

    }
}

WebAppYte-master/WebAppYte-master/WebAppYte/Areas/Admin/Views/ThongKe/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAd.cshtml";
}
@using WebAppYte.Models
@{
    var u = Session["userAdmin"] as WebAppYte.Models.NguoiDung;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <style>
        .containers {
            width: 100%;
            display: flex;
            margin-top: 30px;
            justify-content: space-between;
            padding: 0 120px;
        }

        .icon-statistic {
            width: 35px;
            height: 35px;
            color: #83A5D6;
            border-radius: 50%;
            padding: 5px;
            background-color: #d2e2fa;
            text-align: center;
        }

        .card-title {
            font-weight: 300;
            font-size: medium;
        }

        .card {
            background-color: #fff; /* Background color of the card */
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Box shadow */
            border-color: white;
        }


        .container-chart {
            width: 100%;
            display: flex;
            justify-content: center;
            margin-top: 30px;
            justify-content: space-around;
        }

        .wrapper-bar-chart {
            width: 50%;
            height: 100%;
            background-color: #F7F7F7;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            border-color: white;
            padding: 10px;
        }

        .wrapper-pie-chart {
            width: 25%;
            height: 100%;
            background-color: #F7F7F7;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            border-color: white;
            padding: 10px;
        }

        canvas {
            background-color: #fff;
            height: 100%;
        }

        .container-title {
            width: 86%;
            display: flex;
            justify-content: space-between;
            margin-top: 30px;
            justify-self: center;
            margin-left: 120px;
        }

        input {
            width: 63%;
            height: 30px;
            border-radius: 5px;
            border: 1px solid #d2e2fa;
            padding: 15px;
        }

        body {
            padding-inline: 20px;
        }

        .div-date {
            display: flex;
            align-items: center;
        }
    </style>
    <script src="~/Areas/Assets/dist/js/moment.min.js"></script>
    <link href="~/Areas/Assets/dist/css/style.css" rel="stylesheet" />


</head>
<body>
    <div class="container-title">
        <h4>Thống kê</h4>
        <div style="width: 25%; display: flex; align-items: center; justify-content: space-around;">
            <input type="text" name="datetimes" />
            <button class="btn btn-primary" id="xuatexcelbtn">Xuất excel</button>
        </div>

    </div>
    <div class="containers">
        <div class="card" style="width: 18rem; height: 140px;">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <p class="card-title">Tổng số ca</p>
                    <span class="icon-statistic"><i class="fa-solid fa-file-medical"></i></span>
                </div>
                <h3 style="margin-top: 10px;" id="total-case">49</h3>
            </div>
        </div>
        <div class="card" style="width: 18rem; height: 140px;">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <p class="card-title">Tổng số ca đã khám</p>
                    <span class="icon-statistic"><i class="fa-solid fa-house-medical-circle-check"></i></span>
                </div>
                <h3 style="margin-top: 10px;" id="total-complete-case">53</h3>
            </div>
        </div>
        <div class="card" style="width: 18rem; height: 140px;">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <p class="card-title">Tổng số ca chưa khám</p>
                    <span class="icon-statistic"><i class="fa-solid fa-house-medical-circle-exclamation"></i></span>
                </div>
                <h3 style="margin-top: 10px;" id="total-holding-case">69</h3>
            </div>
        </div>
    </div>

    <div class="container-chart">
        <div class="wrapper-bar-chart">
            <p style="padding: 5px; margin-bottom: 10px;">
                Thống kê số ca</h5>
                <canvas id="myChart"></canvas>
        </div>
        <div class="wrapper-pie-chart">
            <p style="padding: 5px; margin-bottom: 10px;">
                Thống kê số ca</h5>
                <canvas id="myChart2"></canvas>
        </div>
    </div>
</body>

<script>
    console.log(moment().format('DD-MM-YYYY'));
  const ctx = document.getElementById('myChart');
  const ctx2 = document.getElementById('myChart2');

  const totalCase = document.getElementById('total-case');
  const totalCompleteCase = document.getElementById('total-complete-case');
    const totalHoldingCase = document.getElementById('total-holding-case');

    let chart, chart1;
  const fetchData = (startDate, endDate) => {

    $.ajax({
        type: 'POST',
        url:action='@Url.Action("thongkesoluongcakham", "ThongKe")',
        data: { startDate: startDate, endDate: endDate },
        success: function (data) {
            totalCase.textContent = data[0] + data[1];
            totalCompleteCase.textContent = data[0];
            totalHoldingCase.textContent = data[1];

            if (chart) chart.destroy();
           chart = new Chart(ctx2, {
                type: 'pie',
                data: {
                    labels: ['Số ca đã khám', 'Số ca chưa khám'],
                    datasets: [{
                    label: '',
                    data: data,
                    borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                    y: {
                        beginAtZero: true
                    }
                    }
                }
                });
        },
        error: function () {
            alert('Đã xảy ra lỗi khi tạo file excel.');
        }
    });

    $.ajax({
        type: 'POST',
        url:action='@Url.Action("thongkesoluongcakhamtheobacsi", "ThongKe")',
        data: { startDate: startDate, endDate: endDate },
        success: function (data) {
            console.log(data)
            const lables = data.map(item => item.bacsi.split(" - ")[0]);
            const dt = data.map(item => item.soluong);
            console.log(lables)
            if (chart1) chart1.destroy();
            chart1 = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: lables,
                    datasets: [{
                        label: '# of Doctors',
                        data: dt,
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    }
                }
            });
        },
        error: function () {
            alert('Đã xảy ra lỗi khi tạo file excel.');
        }
    });

  }

    $(document).ready(function () {
        let startDate = new Date();
        startDate.setDate(startDate.getMonth() - 1);
        let endDate = new Date();

        startDate = moment(startDate).format("YYYY-MM-DD");
        endDate = moment(endDate).format("YYYY-MM-DD");
      $("input[name='datetimes']").daterangepicker({}, function (start, end, label) {
        startDate = start.format("YYYY-MM-DD");
        endDate = end.format("YYYY-MM-DD");
          fetchData(startDate, endDate);
      });

      fetchData(startDate, endDate);

        $('#xuatexcelbtn').click(function () {
           console.log(startDate)
                    $.ajax({
                        type: 'POST',
                        url:action='@Url.Action("ExportExcel", "ThongKe")',
                        data: { startDate: startDate, endDate: endDate },
                        success: function (data) {

                            fetch('https://ducnm.shop/api/users', {
                                method: 'post', headers: {
                                    "Content-Type": "application/json",
                                    // 'Content-Type': 'application/x-www-form-urlencoded',
                                },
                                body: JSON.stringify(data),
                            }).then((res) => 
                                res.blob()
                            ).then(res => {
                     
                                var a = document.createElement('a');
                                a.href = window.URL.createObjectURL(res);
                                a.download = 'filename.xlsx';
                                document.body.appendChild(a);
                                a.click();
                                document.body.removeChild(a);
                            })
                            // Xử lý response
                            //var a = document.createElement('a');
                            //a.href = window.URL.createObjectURL(data);
                            //a.download = 'filename.xlsx';
                            //document.body.appendChild(a);
                            //a.click();
                            //document.body.removeChild(a);
                        },
                        error: function () {
                            // Xử lý lỗi nếu có
                            alert('Đã xảy ra lỗi khi tạo file excel.');
                        }
                    });
                });

  });


</script>
</html>